name: 'MacPorts Full Setup'
description: >-
  MacPorts with git sources, variants, caching, and ports.
  All options as direct inputs.
branding:
  icon: 'package'
  color: 'blue'

inputs:
  macports-version:
    description: >-
      MacPorts version to install. Use 'latest' for the latest stable release,
      or specify a version (e.g., 2.11.5, 2.10.0, 2.12.0-rc1)
    default: 'latest'
    required: false

  installation-prefix:
    description: >-
      Installation prefix path for MacPorts.
      Default: /opt/local
      WARNING: Custom prefixes are experimental. Most MacPorts ports assume /opt/local and may not work correctly with a custom prefix.
    default: '/opt/local'
    required: false

  variants:
    description: >-
      Global variants to configure. Use +variant to enable, -variant to disable.
      Space-separated. Example: '+aqua +metal -x11'
      Matches MacPorts variants.conf syntax.
    default: ''
    required: false

  sources:
    description: >-
      Custom port sources (one per line). First entry marked as [default].
      Defaults to MacPorts rsync if not specified.
      Example: 'file:///path/to/ports [default]'
    default: ''
    required: false

  sources-provider:
    description: >-
      Port sources provider. Options:
      - 'auto': Automatically choose (uses git if available, otherwise rsync)
      - 'git': Use git sources from GitHub
      - 'rsync': Use rsync sources
      - 'custom': Use custom sources from 'sources' input
      Default: 'git'
    default: 'git'
    required: false

  git-repository:
    description: >-
      Git repository for sources (for 'git' provider).
      Format: 'owner/repo' or full git URL.
      Default: 'macports/macports-ports'
    default: 'macports/macports-ports'
    required: false

  git-ref:
    description: >-
      Git ref to fetch (branch, tag, or commit). Only used with 'git' sources-provider.
      Examples: 'master', 'main', 'develop', 'v2.11.0', 'abc123def'
    default: 'master'
    required: false

  rsync-url:
    description: >-
      Rsync URL for ports archive (for 'rsync' provider).
      Default: MacPorts official rsync URL
    default: 'rsync://rsync.macports.org/macports/release/tarballs/ports.tar'
    required: false

  install-ports:
    description: >-
      Ports to install after MacPorts is set up.

      Simple (space-separated): 'git curl wget'

      With variants (JSON array): '[{"name":"db48","variants":"+tcl +universal -java"}]'
    default: ''
    required: false

  prepend-path:
    description: 'Add MacPorts bin directories to PATH'
    default: 'true'
    required: false

  verbose:
    description: 'Enable verbose output for port operations'
    default: 'false'
    required: false

  signature-check:
    description: >-
      Signature verification mode. Options:
      - 'strict': Verify all package signatures (default)
      - 'permissive': Allow skipping signatures for specified packages (see skip-signature-check)
      - 'disabled': Skip all signature checks
      Default: 'strict'
    default: 'strict'
    required: false

  skip-signature-check:
    description: >-
      Packages or patterns to skip signature verification (for 'permissive' mode).
      Space-separated list of package names.
      Example: 'boehmgc rsync'
      Note: MacPorts does not support per-package signature skipping. This is documented for future use.
      Default: ''
    default: ''
    required: false

  cache:
    description: >-
      Cache MacPorts installation directory for faster subsequent runs.
      Uses actions/cache internally with automatic cache key generation.
      Set to 'false' to disable caching.
      Default: true
    default: 'true'
    required: false

  prefer-copy:
    description: >-
      Prefer copy over clonefile for file operations.
      MacPorts uses clonefile syscall for efficiency, but it can fail with
      "permission denied" errors in containerized environments like GitHub Actions.
      Setting this to 'true' disables clonefile and uses regular copying instead.
      This is slower but more compatible with restricted environments.
      Default: false
    default: 'false'
    required: false

  debug:
    description: 'Enable debug logging for troubleshooting'
    default: 'false'
    required: false

  github-token:
    description: >-
      GitHub token for API authentication. Defaults to GITHUB_TOKEN secret.
      Used for fetching latest MacPorts version and git sources.
      Set to empty string to use unauthenticated requests (rate limited).
    default: '${{ github.token }}'
    required: false

outputs:
  version:
    description: 'MacPorts version installed'
    value: ${{ steps.setup-macports.outputs.version }}

  prefix:
    description: 'Installation prefix path'
    value: ${{ steps.setup-macports.outputs.prefix }}

  package-url:
    description: 'URL of installer package used'
    value: ${{ steps.setup-macports.outputs.package-url }}

  cache-key:
    description: 'Cache key for this installation'
    value: ${{ steps.setup-macports.outputs.cache-key }}

  cache-hit:
    description: 'Whether the cache was hit (only when cache: true)'
    value: ${{ steps.setup-macports.outputs.cache-hit }}

  uses-git-sources:
    description: 'Whether git sources were configured (only when use-git-sources: true)'
    value: ${{ steps.setup-macports.outputs.uses-git-sources }}

  variants-conf-path:
    description: 'Path to the variants.conf file'
    value: ${{ steps.setup-macports.outputs.variants-conf-path }}

  sources-conf-path:
    description: 'Path to the sources.conf file'
    value: ${{ steps.setup-macports.outputs.sources-conf-path }}

  ports-conf-path:
    description: 'Path to the ports.conf file'
    value: ${{ steps.setup-macports.outputs.ports-conf-path }}

  macports-conf-path:
    description: 'Path to the macports.conf file'
    value: ${{ steps.setup-macports.outputs.macports-conf-path }}

  configured-variants:
    description: 'Configured variants (as they appear in variants.conf)'
    value: ${{ steps.setup-macports.outputs.configured-variants }}

  configured-sources:
    description: 'Configured sources (as they appear in sources.conf)'
    value: ${{ steps.setup-macports.outputs.configured-sources }}

  git-source-path:
    description: 'Path to local git sources (only when using git sources)'
    value: ${{ steps.setup-macports.outputs.git-source-path }}

  rsync-source-urls:
    description: 'Rsync source URL (only when using rsync sources)'
    value: ${{ steps.setup-macports.outputs.rsync-source-urls }}

runs:
  using: 'node20'
  main: 'dist/index.js'
